# Generated by Django 2.1 on 2018-10-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='role',
        ),
    ]
