# Generated by Django 2.1 on 2018-10-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20181026_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='Employee',
        ),
    ]
